completed typescript-carousel - Cody Epstein
kepsteen/c0524-code-solutions pull request #57
Opened 2024-06-10 23:25 UTC by kepsteen

![Recording 2024-06-10 at 16 25 44](https://github.com/kepsteen/c0524-code-solutions/assets/118944207/e61c2544-6fb2-4084-84ce-bf4dd9456515)

2024-06-10 23:40 UTC, brandon-moy requested changes
Great job on the carousel! I would like to see you try to optimize it a little bit more though.

2024-06-10 23:40 UTC, brandon-moy commented on typescript-carousel/index.html
> +          ></i>
You have an anchor in this icon but no anchor in the other icon. You don't need the anchor since this isn't linking you to another location.

2024-06-10 23:40 UTC, brandon-moy commented on typescript-carousel/main.ts
> +    id: 'bulbasaur',
What is this array doing for you? It looks like you're only using it for its length to determine if you should set your index to 5 or 0 if you go forward or back at the end. You've queried for all of your `$imageNodeList` elements so why not use that to determine your length?

2024-06-10 23:40 UTC, brandon-moy commented on typescript-carousel/main.ts
> +
You are calling `renderImg` here but also on line 110 which means that your `$carousel` event listener is running `renderImg` twice. In the spirit of DRY (don't repeat yourself) you should try to find a way where you are only running your `renderImg` once per call

2024-06-11 00:11 UTC, kepsteen commented
![Recording 2024-06-10 at 17 10 42](https://github.com/kepsteen/c0524-code-solutions/assets/118944207/42e3fac7-d0e1-4bea-af3d-6d8cfde1624b)

2024-06-11 03:38 UTC, brandon-moy approved these changes
Looks good, approved!

2024-06-11 16:05 UTC, merged